import {
  Settings,
  Boxes,
  ShoppingCart,
  Wallet,
  BarChart3,
  ClipboardCheck,
  Megaphone,
  Users,
  HeartHandshake,
  Sparkles,
} from "lucide-react";

// Configuração central dos 10 módulos do ERP.
// Cada módulo terá sua página de índice; submódulos serão construídos incrementalmente.
export const MODULES = [
  {
    id: "cadastros",
    nome: "Cadastros e Configurações",
    descricao: "Lojas, usuários, produtos, insumos, fornecedores e parâmetros gerais.",
    path: "/admin/cadastros",
    icon: Settings,
    submodulos: [
      "Lojas / Unidades",
      "Usuários e Permissões",
      "Produtos",
      "Insumos",
      "Fornecedores",
      "Unidades de Medida",
      "Categorias Financeiras",
      "Centros de Custo",
      "Formas de Pagamento",
      "Canais de Venda",
      "Parâmetros Gerais",
    ],
  },
  {
    id: "operacoes",
    nome: "Operações",
    descricao: "Compras, estoque, fichas técnicas, produção e inventários.",
    path: "/admin/operacoes",
    icon: Boxes,
    submodulos: [
      "Compras",
      "Notas Fiscais",
      "Estoque",
      "Transferências",
      "Ajustes",
      "Perdas",
      "Fichas Técnicas",
      "Ordens de Produção",
      "Inventários / Contagens",
      "Produção do CD e das Lojas",
    ],
  },
  {
    id: "vendas",
    nome: "Vendas e Caixa",
    descricao: "Fechamento diário, vendas, sangrias e conferência de caixa.",
    path: "/admin/vendas",
    icon: ShoppingCart,
    submodulos: [
      "Fechamento Diário",
      "Vendas por Canal",
      "Vendas por Forma de Pagamento",
      "Sangrias",
      "Despesas Pagas no Caixa",
      "Recebíveis",
      "Conferência de Caixa",
    ],
  },
  {
    id: "financeiro",
    nome: "Financeiro",
    descricao: "Financeiro real e Banco Virtual interno entre CD e lojas.",
    path: "/admin/financeiro",
    icon: Wallet,
    submodulos: [
      "Contas a Pagar",
      "Contas a Receber",
      "Contas Bancárias",
      "Movimentações",
      "Fluxo de Caixa",
      "Conciliação OFX",
      "Banco Virtual — Vendas Internas",
      "Banco Virtual — Débitos / Créditos",
      "Banco Virtual — Saldo por Loja",
      "Banco Virtual — Liquidação Interna",
    ],
  },
  {
    id: "gestao",
    nome: "Gestão e Indicadores",
    descricao: "DRE, CMV, margem, resultado por loja e relatórios.",
    path: "/admin/gestao",
    icon: BarChart3,
    submodulos: [
      "Dashboard",
      "DRE Gerencial",
      "CMV",
      "Margem por Produto",
      "Resultado por Loja",
      "Resultado Consolidado",
      "Relatórios",
    ],
  },
  {
    id: "rotinas",
    nome: "Rotinas Operacionais",
    descricao: "Checklists, tarefas, chamados, manutenção e auditorias.",
    path: "/admin/rotinas",
    icon: ClipboardCheck,
    submodulos: [
      "Checklists",
      "Tarefas",
      "Auditorias",
      "Evidências com Foto",
      "Chamados",
      "Ocorrências",
      "Manutenção Preventiva",
      "Manutenção Corretiva",
      "Ordens de Serviço",
      "Comunicação Operacional",
    ],
  },
  {
    id: "marketing",
    nome: "Marketing e Comercial",
    descricao: "Campanhas, cupons, clientes e performance por canal.",
    path: "/admin/marketing",
    icon: Megaphone,
    submodulos: [
      "Campanhas",
      "Cupons",
      "Promoções",
      "Clientes",
      "Recorrência",
      "Ranking de Clientes",
      "Ticket Médio",
      "Performance por Canal",
      "Recuperação de Inativos",
    ],
  },
  {
    id: "pessoas",
    nome: "Pessoas e RH",
    descricao: "Colaboradores, escalas, ponto, documentos e treinamentos.",
    path: "/admin/pessoas",
    icon: Users,
    submodulos: [
      "Colaboradores",
      "Cargos",
      "Escalas",
      "Ponto Eletrônico",
      "Banco de Horas",
      "Faltas",
      "Atrasos",
      "Solicitações",
      "Atestados",
      "Documentos",
      "Treinamentos",
      "Admissões",
      "Desligamentos",
    ],
  },
  {
    id: "atendimento",
    nome: "Atendimento e Experiência",
    descricao: "Reclamações, avaliações, NPS, cortesias e tratativas.",
    path: "/admin/atendimento",
    icon: HeartHandshake,
    submodulos: [
      "Reclamações",
      "Avaliações",
      "NPS",
      "Ocorrências de Pedidos",
      "Cortesias",
      "Reembolsos",
      "Tratativas",
      "Histórico de Problemas",
    ],
  },
  {
    id: "ia",
    nome: "IA e Integrações",
    descricao: "Agents, webhooks, n8n, WhatsApp e leitura inteligente.",
    path: "/admin/ia",
    icon: Sparkles,
    submodulos: [
      "Agents Internos",
      "Logs de IA",
      "Webhooks",
      "n8n",
      "WhatsApp",
      "iFood (futuro)",
      "Leitura de Notas Fiscais",
      "Leitura de Comprovantes",
      "Análise de Imagens",
      "Alertas Inteligentes",
    ],
  },
];

export const getModule = (id) => MODULES.find((m) => m.id === id);